version: '3.8'
services:
  server:
    # Build the MHFZ server
    build: ./server
    container_name: mhserver
    restart: always
    ports:
      - "127.0.0.1:10200:80"
      - "127.0.0.1:53312:53312"
      - "127.0.0.1:54001:54001"
      - "127.0.0.1:54002:54002"
      - "127.0.0.1:54003:54003"
      - "127.0.0.1:54004:54004"
      - "127.0.0.1:53310:53310"
    networks:
      appNetwork:
        ipv4_address: 172.24.10.1
    extra_hosts:
      - "mhfg.capcom.com.tw:127.0.0.1"
      - "mhf-n.capcom.com.tw:127.0.0.1"
      - "cog-members.mhf-z.jp:127.0.0.1"
      - "www.capcom-onlinegames.jp:127.0.0.1"
      - "srv-mhf.capcom-networks.jp:127.0.0.1"
    command: "sh -sc 'cd /Erupe && go run main.go && tail -f /dev/null'"
  db:
    # Build the PostgreSQL database the server connects to
    build: ./database
    container_name: mhpostgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=erupe
    ports:
      - "10201:5432"
  pgadmin:
    # Connect on host.docker.internal:10201
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mhfz.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
# Expose server on a public IP
networks:
  appNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"